on:
  schedule:
    - cron: '0 13 * * *' # Once per day at 1pm (after Flock rebase)
  pull_request:
  workflow_dispatch: # on button click

name: Build App

jobs:
  build-app_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install FVM
        run: dart pub global activate fvm

      - name: Install Flock with FVM
        run: fvm install

      - name: Download app dependencies using FVM
        run: fvm flutter pub get

  build-app_beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          ref: beta

      - name: Set up Dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install FVM
        run: dart pub global activate fvm

      - name: Install Flock with FVM
        run: fvm install

      - name: Download app dependencies using FVM
        run: fvm flutter pub get

  build-app_stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          ref: stable

      - name: Set up Dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install FVM
        run: dart pub global activate fvm

      - name: Install Flock with FVM
        run: fvm install

      - name: Download app dependencies using FVM
        run: fvm flutter pub get
