on:
  schedule:
    - cron: '0 13 * * *' # Once per day at 1pm
  pull_request:
  workflow_dispatch: # on button click

name: Build App

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install FVM
        run: dart pub global activate fvm

      - name: Flock Version
        run: fvm flutter --version

      - name: Install Flock with FVM
        run: fvm install

      - name: List FVM installs
        run: fvm list

      - name: Download app dependencies using FVM
        run: fvm flutter pub get

